"""Mario Party 8 English Encoding Map"""
translation_map = [
    (b'_', b'/'),
    (b'\x0E\x0D', b'{ICON_MINUS}'),
    (b'\x0E\x0F', b'{ICON_DPAD}'),
    (b'\x0E\x05', b'{ICON_DPAD_LEFT_RIGHT}'),
    (b'\x0E\x03', b'{ICON_ARROW_UP}'),
    (b'\x0E\x0B', b'{ICON_2}'),
    (b'\x0E\x0A', b'{ICON_1}'),
    (b'\x0E\x08', b'{ICON_A_BUTTON}'),
    (b'\x0E\x09', b'{ICON_B_BUTTON}'),
    (b'\x0E\x07', b'{ICON_WIIMOTE}'),
    (b'\x1E\x07',  b'{COLOUR_YELLOW}'),
    (b'\x1E\x06',  b'{COLOUR_CYAN}'),
    (b'\x1E\x05',  b'{COLOUR_GREEN}'),
    (b'\x1E\x08', b'{COLOUR_RESET}'),
    (b'\x1C\x05', b'{DLG_START_1C05}'),
    (b'\x1C\x07', b'{DLG_START_1C07}'),
    (b'\x1C\x09', b'{DLG_START_1C09}'),
    (b'\x1C\x0A', b'{DLG_START_1C0A}'),
    (b'\x1F\x01', b'{STR_PARAM_1}'),
    (b'\x19\x01', b'{NUM_PARAM_1}'),
    (b'?', b'{RIGHT_ARROW}'),
    (b'\x0E', b'{ICON_}'),
    (b'\x0F', b'{BTN_START}'),
    (b'\x0D', b'{BTN_START_ALT}'),
    (b'\x1A', b'{BTN_END}'),
    (b'\x10', b' '),
    (b'\x85', b'.'),
    (b'\\', b'\''),
    (b'=', b'-'),
    (b'\xC2', b'!'),
    (b'\xC3', b'?'),
    (b'\x82', b','),
    (b'\xFF', b'{WAIT_A_PRESS}'),
    (b'\x1B', b'\t'),
]
